# Generated by Django 2.1.5 on 2019-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0002_auto_20190115_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temp_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
