# Generated by Django 2.1.5 on 2019-01-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0003_auto_20190115_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
