# Generated by Django 2.1.5 on 2019-01-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hearts',
            field=models.IntegerField(default='0'),
        ),
    ]
