# Generated by Django 2.1.5 on 2019-01-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0005_auto_20190115_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.FloatField(default='1.0'),
        ),
    ]
