# Generated by Django 2.1.5 on 2019-01-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0007_auto_20190115_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='st_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='st_time',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
