# Generated by Django 2.1.5 on 2019-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0008_auto_20190115_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='st_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
