# Generated by Django 2.1.5 on 2019-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0010_storeinfo_st_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='st_image',
            field=models.ImageField(default='no_image.png', upload_to='storeImages'),
        ),
    ]
