# Generated by Django 2.1.5 on 2019-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0013_auto_20190117_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='st_score',
            field=models.CharField(default='평점 없음', max_length=10),
        ),
    ]
