# Generated by Django 2.1.5 on 2019-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0014_auto_20190117_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='st_score',
            field=models.FloatField(default='0', max_length=10),
        ),
    ]
