# Generated by Django 2.1.5 on 2019-01-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0015_auto_20190117_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='st_score',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
