# Generated by Django 2.1.5 on 2019-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0016_auto_20190117_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='st_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='st_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
