# Generated by Django 2.1.5 on 2019-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0017_auto_20190117_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
            ],
        ),
    ]
