# Generated by Django 2.1.5 on 2019-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWUDot', '0019_auto_20190118_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='no_image.png', upload_to='userImages/%Y/%m/%d'),
        ),
    ]
